spring.application.name=Formation-Service
server.port=9093

# Datasource (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/formationdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Security - OAuth2 Resource Server (Keycloak)

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/e-learning-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/e-learning-realm/protocol/openid-connect/certs

# Multipart (File Upload)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# MinIO Configuration
minio.url=http://localhost:9100
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket.name=formations


# Logging
logging.level.dcc.formationservice=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Consul
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.service-name=Formation-Service
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true

# Health check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
#spring.cloud.consul.discovery.health-check-path=/actuator/health
#spring.cloud.consul.discovery.health-check-interval=10s
