input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [logger_name] {
    mutate {
      add_field => { "service_name" => "student-service" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "student-logs-%{+YYYY.MM.dd}"
  }


  stdout {
    codec => rubydebug
  }
}