#spring.application.name=Gateway-Service
#
## Server port
#server.port=9090
#
## Consul config
##change disvovery
##spring.cloud.consul.host=consul // docker Me
#spring.cloud.consul.port=8500
#spring.cloud.consul.host=localhost
#spring.cloud.consul.discovery.enabled=true
#spring.cloud.consul.discovery.register=true
#spring.cloud.consul.discovery.prefer-ip-address=true
#
## Health check
#spring.cloud.consul.discovery.health-check-path=/actuator/health
#spring.cloud.consul.discovery.health-check-interval=10s
#
## Gateway DEBUG logs
#logging.level.org.springframework.cloud.gateway=DEBUG
#logging.level.org.springframework.cloud.client=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.security=DEBUG
#
#logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=DEBUG
#
## ===== Gateway Dynamic Routing =====
##spring.cloud.gateway.discovery.locator.discovery.enabled=true
##spring.cloud.gateway.discovery.locator.lower-case-service-id=true
## ===== Gateway Dynamic Routing =====
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#
#
## Logging consul
#logging.level.org.springframework.cloud.consul=DEBUG
#
##Forme
#spring.codec.max-in-memory-size=10MB


spring:
  application:
    name: Gateway-Service
